// THIS FILE IS AUTOGENERATED FROM THE classic-companion-scraper PACKAGE. DO NOT MANUALLY EDIT.

import { IGearPlannerData } from 'classic-companion-core'
import deathKnightBloodTankJson from './death-knight-blood-tank.json';
import deathKnightFrostDpsJson from './death-knight-frost-dps.json';
import deathKnightUnholyDpsJson from './death-knight-unholy-dps.json';
import druidBalanceDpsJson from './druid-balance-dps.json';
import druidFeralTankJson from './druid-feral-tank.json';
import druidFeralDpsJson from './druid-feral-dps.json';
import druidRestorationHealerJson from './druid-restoration-healer.json';
import hunterBeastMasteryDpsJson from './hunter-beast-mastery-dps.json';
import hunterMarksmanshipDpsJson from './hunter-marksmanship-dps.json';
import hunterSurvivalDpsJson from './hunter-survival-dps.json';
import mageArcaneDpsJson from './mage-arcane-dps.json';
import mageFireDpsJson from './mage-fire-dps.json';
import mageFrostDpsJson from './mage-frost-dps.json';
import paladinHolyHealerJson from './paladin-holy-healer.json';
import paladinProtectionTankJson from './paladin-protection-tank.json';
import paladinRetributionDpsJson from './paladin-retribution-dps.json';
import priestDisciplineHealerJson from './priest-discipline-healer.json';
import priestHolyHealerJson from './priest-holy-healer.json';
import priestShadowDpsJson from './priest-shadow-dps.json';
import rogueAssassinationDpsJson from './rogue-assassination-dps.json';
import rogueCombatDpsJson from './rogue-combat-dps.json';
import rogueSubtletyDpsJson from './rogue-subtlety-dps.json';
import shamanElementalDpsJson from './shaman-elemental-dps.json';
import shamanEnhancementDpsJson from './shaman-enhancement-dps.json';
import shamanRestorationHealerJson from './shaman-restoration-healer.json';
import warlockAfflictionDpsJson from './warlock-affliction-dps.json';
import warlockDemonologyDpsJson from './warlock-demonology-dps.json';
import warlockDestructionDpsJson from './warlock-destruction-dps.json';
import warriorArmsDpsJson from './warrior-arms-dps.json';
import warriorFuryDpsJson from './warrior-fury-dps.json';
import warriorProtectionTankJson from './warrior-protection-tank.json';

export const SPECIALIZATION_BIS: {[classSpecRoleKebab: string]: {[setName: string]: IGearPlannerData}} = {
	'death-knight-blood-tank': deathKnightBloodTankJson,
	'death-knight-frost-dps': deathKnightFrostDpsJson,
	'death-knight-unholy-dps': deathKnightUnholyDpsJson,
	'druid-balance-dps': druidBalanceDpsJson,
	'druid-feral-tank': druidFeralTankJson,
	'druid-feral-dps': druidFeralDpsJson,
	'druid-restoration-healer': druidRestorationHealerJson,
	'hunter-beast-mastery-dps': hunterBeastMasteryDpsJson,
	'hunter-marksmanship-dps': hunterMarksmanshipDpsJson,
	'hunter-survival-dps': hunterSurvivalDpsJson,
	'mage-arcane-dps': mageArcaneDpsJson,
	'mage-fire-dps': mageFireDpsJson,
	'mage-frost-dps': mageFrostDpsJson,
	'paladin-holy-healer': paladinHolyHealerJson,
	'paladin-protection-tank': paladinProtectionTankJson,
	'paladin-retribution-dps': paladinRetributionDpsJson,
	'priest-discipline-healer': priestDisciplineHealerJson,
	'priest-holy-healer': priestHolyHealerJson,
	'priest-shadow-dps': priestShadowDpsJson,
	'rogue-assassination-dps': rogueAssassinationDpsJson,
	'rogue-combat-dps': rogueCombatDpsJson,
	'rogue-subtlety-dps': rogueSubtletyDpsJson,
	'shaman-elemental-dps': shamanElementalDpsJson,
	'shaman-enhancement-dps': shamanEnhancementDpsJson,
	'shaman-restoration-healer': shamanRestorationHealerJson,
	'warlock-affliction-dps': warlockAfflictionDpsJson,
	'warlock-demonology-dps': warlockDemonologyDpsJson,
	'warlock-destruction-dps': warlockDestructionDpsJson,
	'warrior-arms-dps': warriorArmsDpsJson,
	'warrior-fury-dps': warriorFuryDpsJson,
	'warrior-protection-tank': warriorProtectionTankJson
}